<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ledger</string>
	</array>
	<key>foldingStartMarker</key>
	<string>^\d{4}[/-]\d{2}[/-]\d{2}.*</string>
	<key>foldingStopMarker</key>
	<string>^\s*$</string>
	<key>keyEquivalent</key>
	<string>^~L</string>
	<key>name</key>
	<string>Ledger</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.function.transaction</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.other.date</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.other.date</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>markup.italic.desc</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>markup.underline.desc</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>First line of a transaction: &lt;date&gt;[=&lt;date&gt;] [*!] [(&lt;id&gt;)] [&lt;desc&gt;]</string>
			<key>match</key>
			<string>(?x:
			  ^(\d{4}[/-]\d\d?[/-]\d\d?|\d\d?[/-]\d\d?)       # date
				 (=(\d{4}[/-]\d\d?[/-]\d\d?|\d\d?[/-]\d\d?))?   # optional effective date
				 \s+
				 (
				  (\*.*) |                                      # cleared
					(\!.*) |                                      # pending
					(.*)                                          # uncleared
			   )
			)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.regexp.expression</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Automated transaction</string>
			<key>match</key>
			<string>^=\s(.*)$</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\d{4}[/-]\d\d?[/-]\d\d?|\d\d?[/-]\d\d?)</string>
			<key>name</key>
			<string>string.other.date</string>
		</dict>
		<dict>
			<key>match</key>
			<string>-?\d+([,\.]\d+)*</string>
			<key>name</key>
			<string>constant.numeric.amount</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?x:
      [\$\£\¥\฿\¢\₡\₢\₣\₤\₥\₦\₧\₨\₩\₪\₫\€\₭\₮\₯\¤\₠\₰\₱]|
      AED|AFN|ALL|AMD|ANG|AOA|ARS|AUD|AWG|AZN|BAM|BBD|BDT|BGN|BHD|BIF|BMD|BND|
      BOB|BOV|BRL|BSD|BTN|BWP|BYR|BZD|CAD|CDF|CHE|CHF|CHW|CLF|CLP|CNY|COP|COU|
      CRC|CUC|CUP|CVE|CZK|DJF|DKK|DOP|DZD|EGP|ERN|ETB|EUR|FJD|FKP|GBP|GEL|GHS|
      GIP|GMD|GNF|GTQ|GYD|HKD|HNL|HRK|HTG|HUF|IDR|ILS|INR|IQD|IRR|ISK|JMD|JOD|
      JPY|KES|KGS|KHR|KMF|KPW|KRW|KWD|KYD|KZT|LAK|LBP|LKR|LRD|LSL|LTL|LVL|LYD|
      MAD|MDL|MGA|MKD|MMK|MNT|MOP|MRO|MUR|MVR|MWK|MXN|MXV|MYR|MZN|NAD|NGN|NIO|
      NOK|NPR|NZD|OMR|PAB|PEN|PGK|PHP|PKR|PLN|PYG|QAR|RON|RSD|RUB|RWF|SAR|SBD|
      SCR|SDG|SEK|SGD|SHP|SLL|SOS|SRD|SSP|STD|SVC|SYP|SZL|THB|TJS|TMT|TND|TOP|
      TRY|TTD|TWD|TZS|UAH|UGX|USD|USN|USS|UYI|UYU|UZS|VEF|VND|VUV|WST|XAF|XAG|
      XAU|XBA|XBB|XBC|XBD|XCD|XDR|XFU|XOF|XPD|XPF|XPT|XSU|XTS|XUA|XXX|YER|ZAR|
      ZMK|ZWL
    )</string>
			<key>name</key>
			<string>constant.other.currency</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Keywords that can appear anywhere</string>
			<key>match</key>
			<string>(?x:
       \b([Ee]very|[Dd]ays?|[Ww]eeks?|[Mm]onths?|[Qq]uarters?|[Yy]ears?|
          [Dd]aily|[Ww]eekly|[Bb]iweekly|[Mm]onthly|[Qq]uarterly|[Yy]early|
          [Jj]an(uary)?|[Ff]eb(ruary)?|[Mm]ar(ch)?|[Aa]pr(il)?|[Mm]ay|[Jj]une?|
          [Jj]uly?|[Aa]ug(ust)?|[Ss]ep(tember)?|[Oo]ct(ober)?|[Nn]ov(ember)?|[Dd]ec(ember)?|
          [Tt]his|[Nn]ext|[Ll]ast|[Ii]n|[Ff]rom|[Ss]ince|[Tt]o|[Uu]ntil)\b
     )</string>
			<key>name</key>
			<string>keyword.other</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Keywords that must be preceded by whitespace</string>
			<key>match</key>
			<string>^\s+\b(default|format|nomarket)\b</string>
			<key>name</key>
			<string>keyword.other</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.regexp.expression</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Keywords that must be preceded by whitespace and followed by an expression</string>
			<key>match</key>
			<string>^\s+(assert|check|eval|payee|value)\s+(.*)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.italic.desc</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Keywords that must be preceded by whitespace and followed by a description</string>
			<key>match</key>
			<string>^\s+(note)\s+(.*)$</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.other</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Keywords that must be preceded by whitespace and followed by some identifier</string>
			<key>match</key>
			<string>^\s+(alias)\s+(.*)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.italic.account</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Virtual posting</string>
			<key>match</key>
			<string>^\s+\((([^\s#%|\*;()\]\[] ?)+)\)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.italic.account</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Balancing virtual posting</string>
			<key>match</key>
			<string>^\s+\[(([^\s#%|\*;()\]\[] ?)+)\]</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.bold.account</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Posting</string>
			<key>match</key>
			<string>^\s+(([^\s#%|\*;()\]\[] ?)+)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.italic.desc</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Beginning-of-line keywords followed by a description</string>
			<key>match</key>
			<string>^([@!]?payee)\s+(.*)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>markup.bold.account</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Beginning-of-line keywords followed by an account</string>
			<key>match</key>
			<string>^([@!]?(A|account|apply account|bucket))\s+(([^\s#%|\*;()\]\[] ?)+)$</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.regexp.expression</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Beginning-of-line keywords followed by an expression</string>
			<key>match</key>
			<string>^([@!]?check)\s+(.*)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.bold.account</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.regexp.expression</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Beginning-of-line keywords followed by an account and an expression</string>
			<key>match</key>
			<string>^([@!]?capture)\s+(([^\s#%|\*;()\]\[] ?)+)\s+(.*)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.other</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Beginning-of-line keywords followed by some identifier</string>
			<key>match</key>
			<string>^([@!]?(apply tag|tag|end apply tag|end tag|include))\s(.*)</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Other beginning-of-line keywords</string>
			<key>match</key>
			<string>^[@!]?(end (apply )?account|commodity|define|fixed|endfixed|year|pop|[PYNDCIiOobh]\s+)</string>
			<key>name</key>
			<string>keyword.other</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\;.*$</string>
			<key>name</key>
			<string>comment.line.semi-colon</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Beginning-of-line line comment</string>
			<key>match</key>
			<string>^[#%|\*].*$</string>
			<key>name</key>
			<string>comment.line.number-sign</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^[@!]?(comment|test)</string>
			<key>end</key>
			<string>^[@!]?end (comment|test)|\z</string>
			<key>name</key>
			<string>comment.block</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.ledger</string>
	<key>uuid</key>
	<string>66ECAE19-1421-45CE-AA25-5019FECDB1C9</string>
</dict>
</plist>
